# Generated by Django 2.1.5 on 2022-03-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gacourse',
            old_name='name',
            new_name='title',
        ),
    ]
