# Generated by Django 2.1.5 on 2022-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220322_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gacourse',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
